networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
services: 
  server1-proxy:
    container_name: redes
    image: httpd:latest
    ports: 
      - "8081:8084"
    working_dir: /usr/local/apache2 
    volumes:
      - ./server1-proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro 
      - ./server1-proxy/extra:/usr/local/apache2/conf/extra:ro #ro: é read only
      - ./server1-proxy/static:/usr/local/apache2/htdocs:ro 
    depends_on:
      - server2
      - server3
    dns: 172.20.0.2

  server-dns:
    container_name: dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=bind
    volumes:
      - ./server-dns/named.conf:/etc/bind/named.conf:ro
      - ./server-dns/db.lab:/etc/bind/db.lab:ro
    networks:
      lab_net:
        ipv4_address: 172.20.0.2

  server2:
    image: httpd:latest
    ports:
      - "8080:8083"
    working_dir: /usr/local/apache2
    volumes:
      - ./server2/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./server2/static:/usr/local/apache2/htdocs:ro 
    

  server3:
    image: httpd:latest
    ports:
      - "8082:80"
    working_dir: /usr/local/apache2
    volumes:
      - ./server3/static:/usr/local/apache2/htdocs:ro



    
