services: 
  server1-proxy:
    container_name: redes
    image: httpd:latest
    ports: 
      - "8081:80"
    working_dir: /usr/local/apache2 
    volumes:
      - ./server1-proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro 
      - ./server1-proxy/extra:/usr/local/apache2/conf/extra:ro #ro: é read only
      - ./server1-proxy/static:/usr/local/apache2/htdocs:ro 


  server2:
    image: httpd:latest
    ports:
      - "8080:80"
    working_dir: /usr/local/apache2
    volumes:
      - ./server2/static:/usr/local/apache2/htdocs:ro 
    




    
