options{
    directory "/var/cache/bind";
    
    allow-query{
        127.0.0.1;
        127.20.0.0/24;
    };

    forwarders {
        8.8.8.8;
        1.1.1.1;
    };
    forward only;

    dnssec-validation auto;
    listen-on{ any; };
    listen-on{ any;};

};
zone "lab" {
        type master;
        file "/etc/bind/db.lab";    
};