options{
    directory "/var/cache/bind";
    
    allow-query{any;};

    forwarders {
        8.8.8.8;
        1.1.1.1;
    };
    forward only;

    dnssec-validation auto;
    listen-on{ any; };
    listen-on-v6{ any; };

};
zone "lab" {
        type master;
        file "/etc/bind/db.lab";    
};