port=0

interface=eth0
bind-interfaces

dhcp-authoritative
dhcp-range=172.20.0.50,172.20.0.99,255.255.255.0, 12h

dhcp-option=option:router, 172.20.0.1
dhcp-option=option:dns-server, 172.20.0.2
domain=lab

dhcp-host=02:42:ac:14:00:3c,cliente,172.20.0.60

dhcp-leasefile=/var/lib/dnsmasq/dnsmasq.leases
log-dhcp